### ISSUE TITLE
Codice sorgente

### ISSUE THREAD

**Issue by RobertoDimatteo** [RobertoDimatteo/MAP#6]
Codice del progetto

**Comment by Lunalorla** [comment]
Tutorial per settare e usare JavaFx e Scenebuilder:

- Corso gratuito su Udemy per JavaFx: https://www.udemy.com/course/learn-javafx-tutorials-from-beginners-level/
- Come settare JavaFx su Eclipse: https://youtu.be/bk28ytggz7E (SceneBuilder funziona solo con JavaFx già installato su Eclipse e pc) - quando aggiungi la libreria di javaFx, NON aggiungerla come fa lui a "Classpath" ma aggiungila a "ModulePath", questo si fa se si usano le versioni più recenti di java sdk, tipo la 16, il tizio ne usa una vecchia. - se si lascia creare il module file del progetto, poi non si dovrà cambiare la run configuration perchè non darà problemi.
- Come settare SceneBuilder su Eclipse: https://youtu.be/yngO5WwfZCY - fai attenzione al percorso di installazione che ti mette in automatico, io ho dovuto cambiarlo a mano nel wizard

**Comment by Lunalorla** [comment]
Utilizzo di Javafx e SceneBuilder:

- Tutorial creazione applicazioni grafiche pt.1 su intellij: https://youtu.be/UTdTCpLbYKw
- Tutorial creazione applicazioni grafiche pt.2 su intellij: https://youtu.be/WZRAZhxB1C8
- JavaFX switch scenes: https://youtu.be/hcM-R-YOKkQ
- Switching fast scenes with controller: https://youtu.be/qnwBZveyUtA
- Classe per POP-UP: https://www.geeksforgeeks.org/javafx-alert-with-examples/

**Comment by Lunalorla** [comment]
CSS:
- Tabella codici colori: https://www.w3schools.com/cssref/css_colors.asp
- Button generator: https://toolset.mrw.it/css/button-generator.html
- Styling FX Buttons with CSS: http://fxexperience.com/2011/12/styling-fx-buttons-with-css/
- SceneBuilder User Guide: https://docs.oracle.com/javafx/scenebuilder/1/user_guide/stylesheet-support.htm#CHDJDEFI
- Styling UI Controls with CSS: https://docs.oracle.com/javase/8/javafx/user-interface-tutorial/apply-css.htm#CHDGHCDG
- css instruction guide provided by oracle : https://docs.oracle.com/javase/8/javafx/get-started-tutorial/css.htm#BEIBBBCI
